# Generated by Django 3.1.1 on 2020-11-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(default='welcome to branagram!', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='be the change u want to see in the world', max_length=300),
        ),
    ]
